import os
import json
from typing import Optional, List, Dict, Any

from src.middleware.prompt_injection_detector import PromptInjectionDetector
from src.middleware.pii_secret_redactor import PIISecretRedactor
from src.sandbox.code_execution_engine import CodeSandboxEngine
from src.guardrails.bedrock_guardrails_client import BedrockGuardrailsClient

try:
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.responses import JSONResponse
    from pydantic import BaseModel, Field
    HAS_FASTAPI = True
except ImportError:
    HAS_FASTAPI = False

    class FastAPI:
        def __init__(self, **kwargs): pass
        def get(self, *args, **kwargs): return lambda fn: fn
        def post(self, *args, **kwargs): return lambda fn: fn

    class JSONResponse:
        def __init__(self, status_code: int = 200, content: Any = None):
            self.status_code = status_code
            self.content = content
            self.body = json.dumps(content).encode() if content else b""

    class BaseModel:
        def __init__(self, **kwargs):
            for k, v in kwargs.items():
                setattr(self, k, v)

    def Field(default=..., **kwargs):
        return default

app = FastAPI(
    title="AWS AI Security & OWASP LLM Top 10 Shield",
    description="Production-grade AI Security Shield with Bedrock Guardrails, Edge PII Redaction, and Ephemeral Code Sandboxing.",
    version="1.0.0"
)

# Initialize Security Components
injection_detector = PromptInjectionDetector()
pii_redactor = PIISecretRedactor()
sandbox_engine = CodeSandboxEngine()
bedrock_client = BedrockGuardrailsClient()


# Request / Response Models
class InspectionRequest(BaseModel):
    prompt: str = Field(..., description="Prompt or LLM input payload to inspect")
    check_pii: bool = Field(default=True, description="Enable PII/Secret redaction check")
    check_injection: bool = Field(default=True, description="Enable Prompt Injection check")
    check_guardrails: bool = Field(default=True, description="Enable AWS Bedrock Guardrails evaluation")


class RedactRequest(BaseModel):
    text: str = Field(..., description="Text containing potential secrets or PII")


class SandboxExecuteRequest(BaseModel):
    code: str = Field(..., description="Python code snippet generated by AI model")
    timeout_seconds: Optional[float] = Field(default=2.0, description="Execution timeout limit")


class BedrockEvaluateRequest(BaseModel):
    prompt: str = Field(..., description="Prompt to evaluate against AWS Bedrock Guardrails")
    guardrail_id: Optional[str] = Field(default=None, description="AWS Bedrock Guardrail ID")


@app.get("/health")
def health_check():
    return {
        "status": "HEALTHY",
        "service": "aws-ai-security-shield",
        "version": "1.0.0",
        "security_engines": {
            "prompt_injection_detector": "ACTIVE",
            "pii_secret_redactor": "ACTIVE",
            "code_sandbox_engine": "ACTIVE",
            "bedrock_guardrails_client": "ACTIVE"
        }
    }


@app.post("/shield/inspect")
def inspect_payload(payload: InspectionRequest):
    """
    Executes complete multi-layered security evaluation pipeline across incoming AI prompts.
    """
    prompt = getattr(payload, "prompt", "")
    check_pii = getattr(payload, "check_pii", True)
    check_injection = getattr(payload, "check_injection", True)
    check_guardrails = getattr(payload, "check_guardrails", True)

    results: Dict[str, Any] = {
        "overall_status": "PASSED",
        "risk_level": "LOW",
        "action_taken": "ALLOW"
    }

    # Layer 1: Prompt Injection Audit (LLM01)
    if check_injection:
        injection_res = injection_detector.inspect(prompt)
        results["prompt_injection_analysis"] = injection_res
        if injection_res["is_flagged"]:
            results["overall_status"] = "BLOCKED"
            results["risk_level"] = "CRITICAL"
            results["action_taken"] = "BLOCK_PROMPT_INJECTION"
            results["block_reason"] = f"Prompt Injection / Jailbreak attempt detected: {injection_res['detected_threats']}"
            return JSONResponse(status_code=403, content=results)

    # Layer 2: Edge PII & Secret Redaction (LLM06)
    sanitized_prompt = prompt
    if check_pii:
        redact_res = pii_redactor.redact(prompt)
        results["pii_secret_redaction"] = redact_res
        sanitized_prompt = redact_res["redacted_text"]

    # Layer 3: AWS Bedrock Guardrails Policy Check
    if check_guardrails:
        guardrail_res = bedrock_client.evaluate_guardrail(sanitized_prompt)
        results["bedrock_guardrails_analysis"] = guardrail_res
        if guardrail_res["is_blocked"]:
            results["overall_status"] = "BLOCKED"
            results["risk_level"] = "HIGH"
            results["action_taken"] = "BLOCK_BEDROCK_GUARDRAIL"
            results["block_reason"] = f"Bedrock Guardrail violation: {guardrail_res.get('reasons')}"
            return JSONResponse(status_code=403, content=results)

    results["final_sanitized_prompt"] = sanitized_prompt
    return results


@app.post("/shield/redact")
def redact_text(payload: RedactRequest):
    """
    Zero-Trust PII & AWS Secret Redaction Endpoint.
    """
    text = getattr(payload, "text", "")
    return pii_redactor.redact(text)


@app.post("/shield/sandbox/execute")
def execute_sandboxed_code(payload: SandboxExecuteRequest):
    """
    OWASP LLM02: Safe Code Execution Engine Endpoint.
    """
    code = getattr(payload, "code", "")
    timeout = getattr(payload, "timeout_seconds", 2.0) or 2.0
    engine = CodeSandboxEngine(timeout_seconds=timeout)
    exec_res = engine.execute_code(code)

    if exec_res["status"] == "BLOCKED":
        return JSONResponse(status_code=403, content=exec_res)

    return exec_res


@app.post("/shield/bedrock/evaluate")
def evaluate_bedrock(payload: BedrockEvaluateRequest):
    """
    Evaluates input text directly against AWS Bedrock Guardrails.
    """
    prompt = getattr(payload, "prompt", "")
    guardrail_id = getattr(payload, "guardrail_id", None)
    return bedrock_client.evaluate_guardrail(
        prompt=prompt,
        guardrail_id=guardrail_id
    )


# Native AWS Lambda Handler Entrypoint
def handler(event, context):
    """
    Native AWS Lambda Handler for API Gateway HTTP API v2 integration.
    """
    path = event.get("rawPath", "/health")
    method = event.get("requestContext", {}).get("http", {}).get("method", "GET")
    
    headers = {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "*"
    }

    if method == "OPTIONS":
        return {"statusCode": 200, "headers": headers, "body": ""}

    if path == "/health":
        return {
            "statusCode": 200,
            "headers": headers,
            "body": json.dumps(health_check())
        }

    body_data = {}
    if event.get("body"):
        try:
            body_data = json.loads(event["body"])
        except Exception:
            body_data = {}

    def extract_body(res):
        if isinstance(res, JSONResponse):
            content = getattr(res, "content", None)
            if content is None and hasattr(res, "body"):
                content = json.loads(res.body.decode())
            return res.status_code, content
        return 200, res

    if path == "/shield/inspect" and method == "POST":
        req = InspectionRequest(**body_data)
        status_code, content = extract_body(inspect_payload(req))
        return {
            "statusCode": status_code,
            "headers": headers,
            "body": json.dumps(content)
        }

    if path == "/shield/redact" and method == "POST":
        req = RedactRequest(**body_data)
        status_code, content = extract_body(redact_text(req))
        return {
            "statusCode": status_code,
            "headers": headers,
            "body": json.dumps(content)
        }

    if path == "/shield/sandbox/execute" and method == "POST":
        req = SandboxExecuteRequest(**body_data)
        status_code, content = extract_body(execute_sandboxed_code(req))
        return {
            "statusCode": status_code,
            "headers": headers,
            "body": json.dumps(content)
        }

    if path == "/shield/bedrock/evaluate" and method == "POST":
        req = BedrockEvaluateRequest(**body_data)
        status_code, content = extract_body(evaluate_bedrock(req))
        return {
            "statusCode": status_code,
            "headers": headers,
            "body": json.dumps(content)
        }

    return {
        "statusCode": 404,
        "headers": headers,
        "body": json.dumps({"error": "Endpoint not found", "path": path})
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("src.server:app", host="0.0.0.0", port=8000, reload=True)
